name: nix-hell
version: 666.20260328
license: BSD3
author: "Chris Done"
copyright: "2024 Chris Done, 2026 Harry Pray IV"
synopsis: "Haskell-based shell scripting language with Nix primitives"
dependencies:
- base >=4.17.2.1 && <4.22
- haskell-src-exts
- ghc-prim
- containers
- text
- bytestring
- async
- criterion-measurement
- criterion
- mtl
- directory
- syb
- constraints
- typed-process
- optparse-applicative
- hspec
- QuickCheck
- template-haskell
- unliftio
- vector
- lucid2
- th-lift
- th-orphans
- aeson
- temporary
- these
- time
- filepath
- unix

ghc-options:
  - -Wall
  - -Wno-missing-pattern-synonym-signatures
  - -O2

library:
  source-dirs: src
  exposed-modules:
    - NixHell
  other-modules: []

executables:
  nix-hell:
    main: src/Hell.hs
    dependencies:
      - nix-hell
    ghc-options:
      - -threaded
      - -rtsopts

tests:
  nix-hell-test:
    main: src/Hell.hs
    dependencies:
      - nix-hell
    ghc-options:
      - -main-is
      - Main.specMain
      - -threaded
      - -rtsopts